version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.0.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  version: 2
  default:
    jobs:
      - test
