version: 2
jobs:
  test:
    docker:
      - image: cimg/node:20.11.1
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  version: 2
  default:
    jobs:
      - test
